"""2 migratsiya

Revision ID: 6b8409d0f03c
Revises: 371f97071b82
Create Date: 2025-01-27 18:06:56.402754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8409d0f03c'
down_revision: Union[str, None] = '371f97071b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('user', 'owner', 'admin', name='roletype'), server_default='user', nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('stadiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=13), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('price_per_hour', sa.Numeric(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_stadiums_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stadiums'))
    )
    op.create_index(op.f('ix_stadiums_address'), 'stadiums', ['address'], unique=False)
    op.create_index(op.f('ix_stadiums_location'), 'stadiums', ['location'], unique=False)
    op.create_index(op.f('ix_stadiums_name'), 'stadiums', ['name'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_at', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'countinuing', 'finished', 'canceled', name='bookingstatus'), server_default='not_started', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], name=op.f('fk_bookings_stadium_id_stadiums')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_date_at'), 'bookings', ['date_at'], unique=False)
    op.create_index(op.f('ix_bookings_end_time'), 'bookings', ['end_time'], unique=False)
    op.create_index(op.f('ix_bookings_start_time'), 'bookings', ['start_time'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', name='paymentmethod'), server_default='cash', nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=True),
    sa.Column('exp_date', sa.String(length=5), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declided', 'out_of_balance', name='paymentstatus'), server_default='pending', nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date_at'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_stadiums_name'), table_name='stadiums')
    op.drop_index(op.f('ix_stadiums_location'), table_name='stadiums')
    op.drop_index(op.f('ix_stadiums_address'), table_name='stadiums')
    op.drop_table('stadiums')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
