"""3 migratsiya

Revision ID: 6c008f87a0e9
Revises: 6b8409d0f03c
Create Date: 2025-02-01 11:01:47.287630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c008f87a0e9'
down_revision: Union[str, None] = '6b8409d0f03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadiums', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('stadiums', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_index('ix_stadiums_location', table_name='stadiums')
    op.drop_index('ix_stadiums_name', table_name='stadiums')
    op.create_index(op.f('ix_stadiums_name'), 'stadiums', ['name'], unique=True)
    op.create_index(op.f('ix_stadiums_latitude'), 'stadiums', ['latitude'], unique=False)
    op.create_index(op.f('ix_stadiums_longitude'), 'stadiums', ['longitude'], unique=False)
    op.drop_column('stadiums', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadiums', sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_stadiums_longitude'), table_name='stadiums')
    op.drop_index(op.f('ix_stadiums_latitude'), table_name='stadiums')
    op.drop_index(op.f('ix_stadiums_name'), table_name='stadiums')
    op.create_index('ix_stadiums_name', 'stadiums', ['name'], unique=False)
    op.create_index('ix_stadiums_location', 'stadiums', ['location'], unique=False)
    op.drop_column('stadiums', 'longitude')
    op.drop_column('stadiums', 'latitude')
    # ### end Alembic commands ###
